SELECT TRANSACTION_QTY*UNIT_PRICE AS REVENUE
FROM COFFEESHOP.PUBLIC.SALES;
SELECT MIN(TRANSACTION_TIME)
FROM COFFEESHOP.PUBLIC.SALES;
SELECT MAX(TRANSACTION_TIME)
FROM COFFEESHOP.PUBLIC.SALES;
SELECT
---AGGREGRATE
COUNT(DISTINCT TRANSACTION_ID) AS NUMBER_OF_SALES,
SUM(TRANSACTION_QTY*UNIT_PRICE) AS TOTAL_REVENUE,
SUM(TRANSACTION_QTY) AS NUMBER_OF_UNIT_SOLD,
---DATES
TO_DATE(TRANSACTION_DATE) AS PURCHASE_DATE,
TO_CHAR(TO_DATE(TRANSACTION_DATE), 'YYYYMM') AS MONTH_ID,
DAYNAME(TO_DATE(TRANSACTION_DATE)) AS DAY_OF_WEEK,
---TIME
CASE
WHEN TRANSACTION_TIME BETWEEN '04:00:00' AND '11:59:59' THEN 'MORNING'
WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '15:59:59' THEN 'AFTERNOON'
WHEN TRANSACTION_TIME BETWEEN '16:00:00' AND '20:59:59' THEN 'EVENING'
ELSE 'NIGHT'
END AS TIME_BUCKET,
CASE
WHEN SUM(TRANSACTION_QTY*UNIT_PRICE) BETWEEN 0 AND 10 THEN 'LOW'
WHEN SUM(TRANSACTION_QTY*UNIT_PRICE) BETWEEN 11 AND 49 THEN 'MEDUIM'
ELSE 'HIGH'
END AS SPENDER_BUCKET,
---GROUPS
STORE_LOCATION,
PRODUCT_CATEGORY,
PRODUCT_DETAIL,
PRODUCT_TYPE
FROM COFFEESHOP.PUBLIC.SALES
GROUP BY
PURCHASE_DATE,
MONTH_ID,
DAY_OF_WEEK,
STORE_LOCATION,
PRODUCT_CATEGORY,
PRODUCT_DETAIL,
PRODUCT_TYPE,
TIME_BUCKET
HAVING TOTAL_REVENUE > 0;
